export const flightResults: any[] = [
  {
    fareSourceCode:
      "SUlyTncrMlY4K0YwN3VDVW9mY2FJMytnbCtIK3cweHN2WFlud1h0UlpheE4rUDhYQkVUSlcxWXhWQlk4UER2N0Zwb1U1ZXMya1dCNG0wKzVlQnpudW9xaUcwOW9yajAxZlpiODNBemdMaDhJSzJkNVEwODMwTitQRVluWGlOVWppM0tKb0NnNFJCZFE2Z3FsY1ZRWTFRPT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 0,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "167.52",
      TotalFare: "353.20",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T10:25:00",
        ArrivalDateTime: "2025-02-03T13:00:00",
        stops: 0,
        JourneyDuration: 245,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "565",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "565",
        StopQuantityInfos: [],
        SegmentRef: 0,
        CabinClassCode: "Y",
        RBD: "T",
        FareFamily: "ECO SAVER",
        SeatsRemaining: 9,
        CheckinBaggage: [
          {
            Type: "ADT",
            Value: "25KG",
          },
        ],
        CabinBaggage: [
          {
            Type: "ADT",
            Value: "SB",
          },
        ],
        FareBasisCodes: "TLXAPIN1",
        ItineraryRef: 0,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T13:35:00",
        ArrivalDateTime: "2025-02-13T18:35:00",
        stops: 0,
        JourneyDuration: 210,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "566",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "566",
        StopQuantityInfos: [],
        SegmentRef: 1,
        CabinClassCode: "Y",
        RBD: "L",
        FareFamily: "ECO SAVER",
        SeatsRemaining: 9,
        CheckinBaggage: [
          {
            Type: "ADT",
            Value: "25KG",
          },
        ],
        CabinBaggage: [
          {
            Type: "ADT",
            Value: "SB",
          },
        ],
        FareBasisCodes: "LLXAPIN1",
        ItineraryRef: 1,
      },
    ],
  },
  {
    fareSourceCode:
      "WFFjRUVlTE8vSDIzMTNrTnZFejQ4eW9HaUU5U0ZrejZPcGROWm1zc1h1R0xTS3BjcTRpZXMzU0w2ZHp0aEF2bDY3eG8yQmN5bXhGV3h5RTVhVjB5eVJDYVNtbG1vUXNPYjZUN3J0SUpOY2JFZENaT1pOUlVxeUt4V2NqbFFLb095V2hCZVR0UVJMWDNYOUw1R2ZFaCtBPT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 0,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "167.52",
      TotalFare: "353.20",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T10:25:00",
        ArrivalDateTime: "2025-02-03T13:00:00",
        stops: 0,
        JourneyDuration: 245,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "565",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "565",
        StopQuantityInfos: [],
        SegmentRef: 0,
        CabinClassCode: "Y",
        RBD: "T",
        FareFamily: "ECO SAVER",
        SeatsRemaining: 9,
        CheckinBaggage: [
          {
            Type: "ADT",
            Value: "25KG",
          },
        ],
        CabinBaggage: [
          {
            Type: "ADT",
            Value: "SB",
          },
        ],
        FareBasisCodes: "TLXAPIN1",
        ItineraryRef: 0,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T03:40:00",
        ArrivalDateTime: "2025-02-13T08:50:00",
        stops: 0,
        JourneyDuration: 220,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "564",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "564",
        StopQuantityInfos: [],
        SegmentRef: 2,
      },
    ],
  },
  {
    fareSourceCode:
      "ZHBCejUrQkh2OEYyV0FCdVM4dkhyRlY1K3h3TDI2bkd4WVo3ZVhIQjlPUDFSbVRuVjJiUzMzcVdHK1BsMEZkd0lIemdmcU9XVHdnSDNlbkNDNnZ3dEt5bmZKT0JTMDRQdjFCRkRRS1pTVnAyQ05zVk1OYXpjYzBLditGemNJTUt1Q09yZHBENHBVUHdFanI1UTcvdDFnPT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 0,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "167.52",
      TotalFare: "353.20",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T04:30:00",
        ArrivalDateTime: "2025-02-03T07:10:00",
        stops: 0,
        JourneyDuration: 250,
        Equipment: "388",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "569",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "569",
        StopQuantityInfos: [],
        SegmentRef: 3,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T13:35:00",
        ArrivalDateTime: "2025-02-13T18:35:00",
        stops: 0,
        JourneyDuration: 210,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "566",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "566",
        StopQuantityInfos: [],
        SegmentRef: 1,
        CabinClassCode: "Y",
        RBD: "L",
        FareFamily: "ECO SAVER",
        SeatsRemaining: 9,
        CheckinBaggage: [
          {
            Type: "ADT",
            Value: "25KG",
          },
        ],
        CabinBaggage: [
          {
            Type: "ADT",
            Value: "SB",
          },
        ],
        FareBasisCodes: "LLXAPIN1",
        ItineraryRef: 1,
      },
    ],
  },
  {
    fareSourceCode:
      "L2VFTStVL05OY2RqOUUyS2QwOGN0SzFDWm5yZUFYbWJuRzBTVEtDcFQrSDZSbTk5elVpdTVCeG4zWVNiMXczSm9tcmk4UE5LS3IvVzBpRDNRU3I4aHZNZTlITHpFK0tTY3JINWR6MTJrbHJKd25KK01aOEk2M0FWbnZzWWpxOG10M3Erd1QveWZpdjQ1ckswWHVvQU9BPT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 0,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "167.52",
      TotalFare: "353.20",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T04:30:00",
        ArrivalDateTime: "2025-02-03T07:10:00",
        stops: 0,
        JourneyDuration: 250,
        Equipment: "388",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "569",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "569",
        StopQuantityInfos: [],
        SegmentRef: 3,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T03:40:00",
        ArrivalDateTime: "2025-02-13T08:50:00",
        stops: 0,
        JourneyDuration: 220,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "564",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "564",
        StopQuantityInfos: [],
        SegmentRef: 2,
      },
    ],
  },
  {
    fareSourceCode:
      "ekRlcWZVWEZJQ2NpallKWEJSbjFEcUZJR2M2TXZNMTQyQ2IxZFJ1eHNFbzY4TWhlcElnZTdaMm5CemwwUE8yMlFyWU5TOFZqbXhsdy9SNis3cGNSMktxTDVYR0h0VThiUGlZc1poMmtKNStKckVrRTFySGJKSmpBWWs3QW1ERXg1VVdjUzI4RmxLeFZnNXdMMmRxcmtBPT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 1,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "178.71",
      TotalFare: "364.95",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T20:20:00",
        ArrivalDateTime: "2025-02-03T23:00:00",
        stops: 0,
        JourneyDuration: 250,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "567",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "567",
        StopQuantityInfos: [],
        SegmentRef: 4,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T13:35:00",
        ArrivalDateTime: "2025-02-13T18:35:00",
        stops: 0,
        JourneyDuration: 210,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "566",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "566",
        StopQuantityInfos: [],
        SegmentRef: 1,
        CabinClassCode: "Y",
        RBD: "L",
        FareFamily: "ECO SAVER",
        SeatsRemaining: 9,
        CheckinBaggage: [
          {
            Type: "ADT",
            Value: "25KG",
          },
        ],
        CabinBaggage: [
          {
            Type: "ADT",
            Value: "SB",
          },
        ],
        FareBasisCodes: "LLXAPIN1",
        ItineraryRef: 1,
      },
    ],
  },
  {
    fareSourceCode:
      "alI1SVNpWUZyZEhkNkVJQU90R2pWZWdMejRYTjAwNFI4YUo2L1dpTGtQMy9hQnlWZCtlbjcrN0U3R0grNjRJRUxiWnBxUE9ra2ozbWJ0MDh6KzNreHBXUThuVFJ6K2FxVFU1d2Z2RGhMZ2ZnWjh6VGlpNmRWdVJUWXh6QTZJcitSVEkybDdHWEwrQ1VKVUlrQndvZ2xnPT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 1,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "178.71",
      TotalFare: "364.95",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T20:20:00",
        ArrivalDateTime: "2025-02-03T23:00:00",
        stops: 0,
        JourneyDuration: 250,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "567",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "567",
        StopQuantityInfos: [],
        SegmentRef: 4,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T03:40:00",
        ArrivalDateTime: "2025-02-13T08:50:00",
        stops: 0,
        JourneyDuration: 220,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "564",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "564",
        StopQuantityInfos: [],
        SegmentRef: 2,
      },
    ],
  },
  {
    fareSourceCode:
      "WlUvVndyTFpmRGcybXhaUCtIa0FVNDRlMHlXQ1R4SjlnTG5tR3oxem10LzZTbWN3U3JoclhlVDFoQm1pVURqb1N1UFlRLzkzdHJsZllrelVISTJrNXBFQmwvSkRMc2gvMWtuQVljZDZ1eVRadkZOWVFKMVU4UVNGNU9oaE1PT2hxZlFOT0hYMkVHNkFrSkhYMWdJM2JRPT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 1,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "178.71",
      TotalFare: "364.95",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T10:25:00",
        ArrivalDateTime: "2025-02-03T13:00:00",
        stops: 0,
        JourneyDuration: 245,
        Equipment: "77W",
        OperatingCarrierCode: "GK",
        OperatingFlightNumber: "565",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "565",
        StopQuantityInfos: [],
        SegmentRef: 0,
        CabinClassCode: "Y",
        RBD: "T",
        FareFamily: "ECO SAVER",
        SeatsRemaining: 9,
        CheckinBaggage: [
          {
            Type: "ADT",
            Value: "25KG",
          },
        ],
        CabinBaggage: [
          {
            Type: "ADT",
            Value: "SB",
          },
        ],
        FareBasisCodes: "TLXAPIN1",
        ItineraryRef: 0,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T21:25:00",
        ArrivalDateTime: "2025-02-14T02:30:00",
        stops: 0,
        JourneyDuration: 215,
        Equipment: "388",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "568",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "568",
        StopQuantityInfos: [],
        SegmentRef: 5,
      },
    ],
  },
  {
    fareSourceCode:
      "ME5FVnY3QjZCN2s3eU11TkRiRmhqeTNsSjQwLzQzU1pWRUR1VkxLc0piWFhNM0oyYzFzN1hBYkhMSUdwOHVQVndDQXRFU0ZTUktlSFphaldmZWkvb0lya3B1MlROMmpnbjBKMXloNjBHZG1tZDZlQnpuNFRkZDRteGdiSlZTTEJTb0dzbEhQT1hueS9kbzJRTlJudDN3PT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 1,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "178.71",
      TotalFare: "364.95",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T04:30:00",
        ArrivalDateTime: "2025-02-03T07:10:00",
        stops: 0,
        JourneyDuration: 250,
        Equipment: "388",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "569",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "569",
        StopQuantityInfos: [],
        SegmentRef: 3,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T21:25:00",
        ArrivalDateTime: "2025-02-14T02:30:00",
        stops: 0,
        JourneyDuration: 215,
        Equipment: "388",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "568",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "568",
        StopQuantityInfos: [],
        SegmentRef: 5,
      },
    ],
  },
  {
    fareSourceCode:
      "YW1QeFRGa2xZdWZRZVRKZW1ZbEVKaXdiNVB3aHQvMlNWWUNpYTdLTk1tekE5MmhvbkZ3ZUNCays0RkJZKzJFQTM4eEdYVUxIS0k3RFNPRkFqaG11N3hEUUI1eWZKMkZxN3phajN6RDBiUng3Y0pFVVJLRmgvVXZCNXp2QTRTMy9lTCtBOHBqdFZxeUp2U1gwdjBhdklnPT0=",
    fares: {
      FareType: "Public",
      Currency: "USD",
      FareRef: 2,
      PaxType: "ADT",
      Quantity: 1,
      BaseFare: "189.84",
      TotalFare: "376.62",
    },
    penaltiesData: {
      PaxType: "ADT",
      RefundPenaltyAmount: "10000",
      RefundAllowed: true,
      Currency: "INR",
      ChangePenaltyAmount: "3000",
      ChangeAllowed: true,
    },
    originDestinations: [
      {
        legIndicator: "0",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Bangalore",
        arrival_airport: "Dubai Intl",
        DepartureAirportLocationCode: "BLR",
        ArrivalAirportLocationCode: "DXB",
        DepartureDateTime: "2025-02-03T20:20:00",
        ArrivalDateTime: "2025-02-03T23:00:00",
        stops: 0,
        JourneyDuration: 250,
        Equipment: "77W",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "567",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "567",
        StopQuantityInfos: [],
        SegmentRef: 4,
      },
      {
        legIndicator: "1",
        operating_airline: "Emirates",
        marketing_airline: "Emirates",
        departure_airport: "Dubai Intl",
        arrival_airport: "Bangalore",
        DepartureAirportLocationCode: "DXB",
        ArrivalAirportLocationCode: "BLR",
        DepartureDateTime: "2025-02-13T21:25:00",
        ArrivalDateTime: "2025-02-14T02:30:00",
        stops: 0,
        JourneyDuration: 215,
        Equipment: "388",
        OperatingCarrierCode: "EK",
        OperatingFlightNumber: "568",
        MarketingCarriercode: "EK",
        MarketingFlightNumber: "568",
        StopQuantityInfos: [],
        SegmentRef: 5,
      },
    ],
  },
];
